### ISSUE TITLE
Splitting the JS and PHP

### ISSUE THREAD

**Issue by httpoz** [BRACKETS-by-TRIAD/admin-ui#2]
Would you guys be open to splitting the js into a separate node package for better dependency management etc.

**Comment by palypster** [comment]
We have already that on our TODO list, but it's not our priority at the moment. But of course, any pulls are welcome ;)

**Comment by httpoz** [comment]
I have just created a repo here [WIP](https://github.com/httpoz/adminui-frontend) and pulled in the SASS in this repo. I also pulled CoreUI via npm and I still have to move the vue files. Your guidance/input would be appreciated to get this inline with the direction you guys are taking.

**Comment by httpoz** [comment]
Accidentally closed the issue.

**Comment by matejminar** [comment]
this is exactly what we are planning to do, however it is still in the pipeline...

we will be addressing this in the near future, so I will keep you informed ;)

**Comment by matejminar** [comment]
Hey, we have made a major overhaul of the frontend assets in the latest release and moved base components(along with other frontend stuff) into npm package. Feel free to check it out!
